// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcllxqteemgwenykvxih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbGx4cXRlZW1nd2VueWt2eGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTI1MDIsImV4cCI6MjA2NjA4ODUwMn0.IeAZy_BXlnO84GAgeRhRSPiJozHtUjoNSSjGoVvpuZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);